### ISSUE TITLE
Add light syntax for single scenarios yaml files

### ISSUE THREAD

**Issue by hhalex** [Bloom-Perf/yaml-pptr#18]
```
location: "http://test.com"
steps:
  - wait: 3
  - click: 
        selectorXpath: "xpath"
```
